#!/usr/bin/env python
"""
Bronze‑Tier Dashboard Updater

Reads `status.json` (generated by the filesystem watcher) and updates
`Dashboard.md` with the latest counts of new items, in‑progress items,
and completed items.
"""

import json
from pathlib import Path

# ----- Paths -----
STATUS_FILE   = Path("status.json")
DASHBOARD_MD  = Path("Dashboard.md")
# -----------------

def load_status():
    if not STATUS_FILE.exists():
        return {"items": []}
    try:
        with open(STATUS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError:
        return {"items": []}

def compute_counts(status):
    total = len(status["items"])
    # Simple heuristic: last three events are categorized by keyword
    new_count = sum(1 for e in status["items"] if "new_item" in e.get("event", ""))
    # In‑progress items are those that have been moved to Needs_Action folder
    in_progress = total - new_count  # placeholder logic
    done_count = 0  # will be filled later by a “complete” action
    return {"new_items_count": new_count, "in_progress_count": in_progress, "done_count": done_count}

def render_markdown(counts):
    today = Path(".").stat().st_mtime  # placeholder for current date
    from datetime import datetime
    current_date = datetime.utcnow().strftime("%Y-%m-%d")
    return f"""# Dashboard

## Overview
This dashboard tracks the status of the AI Employee's core workflows,
recent activity, and key metrics.

## Sections
- [[Inbox]] – New items awaiting action
- [[Needs_Action]] – Items currently being processed
- [[Done]] – Completed items

## Recent Activity
- Last check: `{current_date}`
- New items: `{counts['new_items_count']}`
- Items in progress: `{counts['in_progress_count']}`
- Completed items: `{counts['done_count']}"

    ## Metrics
- **Revenue (today):** $0.00
- **Bottlenecks:** None identified

> *Auto‑generated by the Bronze‑Tier automation scripts.*"""

def main():
    status = load_status()
    counts = compute_counts(status)
    new_md = render_markdown(counts)
    with open(DASHBOARD_MD, "w", encoding="utf-8") as f:
        f.write(new_md)
    print(f"✅ Updated {DASHBOARD_MD} with counts from status.json")

if __name__ == "__main__":
    main()