#!/usr/bin/env python
"""
Silver-Tier Dashboard Updater (Agent Skill)

Reads vault state (status.json, Plans/, Pending_Approval/, Approved/,
Rejected/, Done/, Logs/) and regenerates Dashboard.md with Silver-tier
counts: new items, in-progress, plans, pending approvals, completed,
recent events, and recent approval actions.
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path


def find_vault_root() -> Path:
    here = Path(__file__).resolve().parent
    for candidate in [here, *here.parents]:
        if (candidate / "Inbox").is_dir() and (candidate / "Dashboard.md").is_file():
            return candidate
    return Path.cwd()


ROOT = find_vault_root()
STATUS_FILE = ROOT / "status.json"
DASHBOARD_MD = ROOT / "Dashboard.md"
INBOX_DIR = ROOT / "Inbox"
NEEDS_ACTION = ROOT / "Needs_Action"
DONE_DIR = ROOT / "Done"
PLANS_DIR = ROOT / "Plans"
PENDING_DIR = ROOT / "Pending_Approval"
APPROVED_DIR = ROOT / "Approved"
REJECTED_DIR = ROOT / "Rejected"
LOGS_DIR = ROOT / "Logs"


def load_status():
    if not STATUS_FILE.exists():
        return {"items": []}
    try:
        with open(STATUS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError:
        return {"items": []}


def count_files(directory: Path) -> int:
    if not directory.exists():
        return 0
    return sum(1 for p in directory.iterdir() if p.is_file() and not p.name.startswith("."))


def load_recent_events(limit: int = 5) -> list:
    """Return recent events from status.json + approval logs."""
    events = []

    # From status.json (watcher events)
    status = load_status()
    for item in status.get("items", [])[-limit:]:
        ts = datetime.fromtimestamp(item.get("timestamp", 0), tz=timezone.utc).strftime("%Y-%m-%d %H:%M")
        events.append(f"{ts} | {item.get('event', 'event')} | {item.get('file', '')}")

    # From approval logs (most recent)
    if LOGS_DIR.exists():
        log_files = sorted(LOGS_DIR.glob("*.json"), reverse=True)
        for log_file in log_files[:limit]:
            try:
                entries = json.loads(log_file.read_text(encoding="utf-8"))
                for entry in reversed(entries[-limit:]):
                    ts = entry.get("timestamp", "")[:16].replace("T", " ")
                    action = entry.get("action_type", "action")
                    target = entry.get("target", "")
                    result = entry.get("result", "")
                    events.append(f"{ts} | {action} | {target} | {result}")
            except (json.JSONDecodeError, KeyError):
                pass

    # Sort by timestamp descending and limit
    events.sort(reverse=True)
    return events[:limit]


def compute_counts():
    return {
        "new_items_count": count_files(INBOX_DIR),
        "in_progress_count": count_files(NEEDS_ACTION),
        "plans_count": count_files(PLANS_DIR),
        "pending_approvals_count": count_files(PENDING_DIR),
        "done_count": count_files(DONE_DIR),
        "total_events": len(load_status().get("items", [])),
    }


def render_markdown(counts, recent_events):
    current_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    events_md = ""
    if recent_events:
        for e in recent_events:
            events_md += f"- `{e}`\n"
    else:
        events_md = "- (none)\n"

    return f"""# Dashboard

## Overview
This dashboard tracks the status of the AI Employee's core workflows,
recent activity, and key metrics.

## Sections
- [[Inbox]] – New items awaiting action
- [[Needs_Action]] – Items currently being processed
- [[Plans]] – Reasoning artifacts (Plan.md)
- [[Pending_Approval]] – Awaiting human decision
- [[Approved]] – Approved actions ready to execute
- [[Rejected]] – Declined actions
- [[Done]] – Completed items
- [[Logs]] – Audit trail

## Counts
- **New (Inbox):** `{counts['new_items_count']}`
- **In Progress (Needs_Action):** `{counts['in_progress_count']}`
- **Plans:** `{counts['plans_count']}`
- **Pending Approval:** `{counts['pending_approvals_count']}`
- **Completed (Done):** `{counts['done_count']}`
- **Total watcher events:** `{counts['total_events']}`

## Recent Activity (last {len(recent_events)} events)
{events_md}

## Metrics
- **Revenue (today):** $0.00
- **Bottlenecks:** None identified

> *Auto-generated by the Silver-Tier automation scripts.*"""


def main():
    counts = compute_counts()
    recent_events = load_recent_events()
    new_md = render_markdown(counts, recent_events)
    with open(DASHBOARD_MD, "w", encoding="utf-8") as f:
        f.write(new_md)
    print(f"✅ Updated {DASHBOARD_MD} with Silver-tier counts")


if __name__ == "__main__":
    main()