#!/usr/bin/env python
"""
Bronze-Tier Dashboard Updater (Agent Skill)

Reads `status.json` (generated by the filesystem watcher) and updates
`Dashboard.md` with the latest counts of new items, in-progress items,
and completed items.

New items are files still sitting in `Inbox/`.
In-progress items are files currently in `Needs_Action/`.
Done items are files in `Done/`.
"""

import json
from datetime import datetime, timezone
from pathlib import Path

# ----- Paths -----
def find_vault_root() -> Path:
    here = Path(__file__).resolve().parent
    for candidate in [here, *here.parents]:
        if (candidate / "Inbox").is_dir() and (candidate / "Dashboard.md").is_file():
            return candidate
    return Path.cwd()


ROOT = find_vault_root()
STATUS_FILE = ROOT / "status.json"
DASHBOARD_MD = ROOT / "Dashboard.md"
INBOX_DIR = ROOT / "Inbox"
NEEDS_ACTION = ROOT / "Needs_Action"
DONE_DIR = ROOT / "Done"


def load_status():
    if not STATUS_FILE.exists():
        return {"items": []}
    try:
        with open(STATUS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError:
        return {"items": []}

def count_files(directory: Path) -> int:
    return sum(1 for p in directory.iterdir() if p.is_file() and not p.name.startswith("."))

def compute_counts(status):
    new_count = count_files(INBOX_DIR)
    in_progress = count_files(NEEDS_ACTION)
    done_count = count_files(DONE_DIR)
    return {
        "new_items_count": new_count,
        "in_progress_count": in_progress,
        "done_count": done_count,
        "total_events": len(status.get("items", [])),
    }

def render_markdown(counts):
    current_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return f"""# Dashboard

## Overview
This dashboard tracks the status of the AI Employee's core workflows,
recent activity, and key metrics.

## Sections
- [[Inbox]] – New items awaiting action
- [[Needs_Action]] – Items currently being processed
- [[Done]] – Completed items

## Recent Activity
- Last check: `{current_date}`
- New items: `{counts['new_items_count']}`
- Items in progress: `{counts['in_progress_count']}`
- Completed items: `{counts['done_count']}`
- Total watcher events logged: `{counts['total_events']}`

## Metrics
- **Revenue (today):** $0.00
- **Bottlenecks:** None identified

> *Auto-generated by the Bronze-Tier automation scripts.*"""

def main():
    status = load_status()
    counts = compute_counts(status)
    new_md = render_markdown(counts)
    with open(DASHBOARD_MD, "w", encoding="utf-8") as f:
        f.write(new_md)
    print(f"✅ Updated {DASHBOARD_MD} with counts from status.json")

if __name__ == "__main__":
    main()
